### ISSUE TITLE
bugs listed in faults_found_by_quickcheck.md

### ISSUE THREAD

**Issue by dan-da** [davidrusu/bft-crdts#12]
Have the issues listed [here](https://github.com/davidrusu/bft-crdts/blob/master/faults_found_by_quickcheck.md) been resolved?  If so, perhaps the file should be removed or updated.

**Comment by davidrusu** [comment]
Yep, all those issues have been resolved, I'll get rid of this log :+1:

**Comment by davidrusu** [comment]
Removed in https://github.com/davidrusu/bft-crdts/commit/aa736f3166b4e8772e3ba640c30563da624e74dc
